In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 305.2 kB/s eta 0:00:39
   - -------------------------------------- 0.5/12.3 MB 305.2 kB/s eta 0:00:39
   - -------------------------------------- 0.5/12.3 MB 305.2 kB/s eta 0:00:39
   - -------------------------------------- 0.5/12.3 MB 305.2 kB/s eta 0:00:39
   - -------------------------------------- 0.

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
import numpy as np


In [3]:
print(np.__version__)


2.3.4


In [5]:
list1 =[1,2,3,4]
print(list)
#when we print list it separate with comaas .

[1, 2, 3, 4]


In [8]:
arr_list1 = np.array(list1)
print(arr_list1)
#when we print array it doesnt seprate wirth comaas. 1d array.

[1 2 3 4]


In [9]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [27]:
#3d array .
lst1 =[1,2,3,4]
lst2 =[7,7,5,2]
lst3=[4,5,6,6]
arr_lst1_23 = np.array([[lst1,lst2,lst3]])
print(arr_lst1_23)



[[[1 2 3 4]
  [7 7 5 2]
  [4 5 6 6]]]


In [28]:
print(arr_lst1_23.ndim)

3


In [30]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [4]:
# array attributes 
import numpy as np
arr = np.array([[1,2,3],[3,4,5]])
print("shape : ",arr.shape)
print("size :  ",arr.size)
print("data type : ",arr.dtype)
print("dimension : ",arr.ndim)

shape :  (2, 3)
size :   6
data type :  int64
dimension :  2


In [5]:
#1.HW create 2 arrays 1d and 3d and find its attribute 
#1d array
arr1d =np.array([1,2,3,4,5,6,7])
print("1d array : ",arr1d)
print("shape    :",arr1d.shape)
print("size     :",arr1d.size)
print("datatype :",arr1d.dtype)
print("dimension:",arr1d.ndim)
print("\n")
arr3d =np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3d array : ",arr3d)
print("shape    : ",arr3d.shape)
print("size     : ",arr3d.size)
print("datatype : ",arr3d.dtype)
print("dimension: ",arr3d.ndim)

1d array :  [1 2 3 4 5 6 7]
shape    : (7,)
size     : 7
datatype : int64
dimension: 1


3d array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape    :  (3, 3)
size     :  9
datatype :  int64
dimension:  2


In [6]:
#array initalized method 
#1.zeros array 
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#2. ones array
one_arr =np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
#3. full array
full_arr = np.full((3,3),7)
print(full_arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [40]:
#4. identity matrix
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#5. empty array
print(np.empty((5,4)))

[[2.12199579e-314 4.24399158e-314 4.24399158e-314 6.36598737e-314]
 [6.23058368e-307 2.22526399e-307 6.23053614e-307 7.56592338e-307]
 [1.60216183e-306 7.56602523e-307 3.56043054e-307 1.37961641e-306]
 [2.22518251e-306 1.33511969e-306 6.23037657e-307 6.23053954e-307]
 [9.34609790e-307 8.45593934e-307 9.34600963e-307 1.86921143e-306]]


In [45]:
#6. evenly space array 
print(np.arange(1,6,2))

[1 3 5]


In [47]:
#7.specific number of equal space values between range 
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


In [50]:
#8.random array for float values
ran_arr =np.random.rand(3,4)
print(ran_arr)
#but this gives all the value in float 

[[0.78987318 0.21992327 0.67591812 0.07360108]
 [0.80326379 0.7801708  0.4959815  0.63915799]
 [0.52208711 0.90589405 0.45078642 0.46877714]]


In [52]:
 #9. random array with integer value 
ran_arr =np.random.randint(1,10,(3,3))
print(ran_arr)

[[3 8 2]
 [2 1 2]
 [3 5 5]]


In [11]:
#array indexing and slicling in 1d array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [12]:
print(a[0])
print(a[-1])

1
5


In [19]:
#slicing in 1d array a[start:stop:steps]
aa=np.array([1,2,3,4,5])
print(aa[0:3]) # first three element 
print(aa[-3:]) # last three element 
print(aa[-4:-1]) # middle three element 
print(aa[0::2]) # whole array with steps 

[1 2 3]
[3 4 5]
[2 3 4]
[1 3 5]


In [21]:
#array indexing and slicling in 2d array
_2darr = np.array([[1,2,3],[4,5,6]])
print(_2darr)

[[1 2 3]
 [4 5 6]]


In [22]:
#printing 4 
print(_2darr[1][0])
#printing 2 
print(_2darr[0][1])
#printing 6
print(_2darr[1][2])

4
2
6


In [24]:
#slicing in 2d array 
print(_2darr[: ,1]) # element of each first colowmn 
#where value before ',' is slicing and after ',' is colomn you wants to print 

[2 5]


In [27]:
#slicing in 3d array 
arr3 =np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(arr3[: ,1]) #all 1st colomn value
print(arr3[: ,2]) # all 2nd colowmn value 

[2 5 8]
[3 6 9]


In [30]:
#colowmns value with slicing with skiping or jumping value within the given gap
print(arr3[::2,1]) #jumping value in first colownm
print(arr3[::2,2]) #jumping value in last colownm

[2 8]
[3 9]


In [33]:
print(arr3[::2,1:2]) #we can slicing in both part 
print(arr3[::2,0:1])

[[2]
 [8]]
[[1]
 [7]]


In [41]:
#array reshaping and flattening 
#1. array reshaping accoring to user
arrr =np.array([1,2,3,4,5,5,6,7])
print(arrr)
print("reshaped array")
reshaped_arr = arrr.reshape([4,2])#reshape in 4 rows and 2 colowmn 
print(reshaped_arr)
reshaped_arr = arrr.reshape([2,4])#reshape in 2 rows and 4 colowmn 
print(reshaped_arr)

[1 2 3 4 5 5 6 7]
reshaped array
[[1 2]
 [3 4]
 [5 5]
 [6 7]]
[[1 2 3 4]
 [5 5 6 7]]


In [45]:
#flattening a array 
print("before flatten :")
print(reshaped_arr)
print("after flatten :")
print(reshaped_arr.flatten())


before flatten :
[[1 2 3 4]
 [5 5 6 7]]
after flatten :
[1 2 3 4 5 5 6 7]


In [49]:
#array stacking 
#1.vertical stacking 
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
print(np.vstack((a1,a2)))# vertical stacking row-wise // and converted in 2d array 
#2.horizontal stacking 
print("\n")
print(np.hstack((a1,a2))) # horizontal stacking colowmn-wise // remain same 1d array  

[[1 2 3 4]
 [5 6 7 8]]


[1 2 3 4 5 6 7 8]


In [64]:
#array splitting 
#1.vertical splitting 
c=np.array([[1,2,3],[4,5,6]]) #split the row  
print(c)
print(np.vsplit(c,2))


[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [63]:
#2.horizontal spilting 
hsplit = np.hsplit(c,3) #split the colwmn
for ar in hsplit:
    print(ar)
    

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [66]:
# mathematical operations on the array
a=np.array([12,30,45,60])
print(a)
print(a+5)
print(a-5)
print(a*5)
print(a/5)


[12 30 45 60]
[17 35 50 65]
[ 7 25 40 55]
[ 60 150 225 300]
[ 2.4  6.   9.  12. ]


In [67]:
#some mathmatical function 
b=np.array([2,3,44])
print(b)


[ 2  3 44]


In [68]:
print(np.square(b))
print(np.sqrt(b))

[   4    9 1936]
[1.41421356 1.73205081 6.63324958]


In [69]:
# mathematical operation on multiple arrays
c=np.array([1,2,3,4])
d=np.array([4,3,5,6])
print(c)
print(d)

[1 2 3 4]
[4 3 5 6]


In [70]:
print(np.add(c,d))
print(np.subtract(c,d))
print(np.divide(c,d))
print(np.multiply(c,d))

[ 5  5  8 10]
[-3 -1 -2 -2]
[0.25       0.66666667 0.6        0.66666667]
[ 4  6 15 24]


In [71]:
#dot product sum of product of their corresponding elements 
aa=np.array([1,2,3,4,5])
bb=np.array([6,7,8,9,7])
print(aa)
print(bb)


[1 2 3 4 5]
[6 7 8 9 7]


In [72]:
print(np.dot(aa,bb))

115


In [74]:
#transpose of a matrix

matrix =np.array([[1,2,3],[4,4,5]])
print(matrix)

[[1 2 3]
 [4 4 5]]


In [76]:
print(matrix.T)

[[1 4]
 [2 4]
 [3 5]]


In [77]:
#statical function 
arr2d =np.array([[2,3,4],[4,3,5]])
print(arr2d)

[[2 3 4]
 [4 3 5]]


In [80]:
print(np.sum(arr2d))#for adding element inside the array
print(np.mean(arr2d))#mean
print(np.median(arr2d))#median
print(np.std(arr2d))#standard deavation 
print(np.min(arr2d))#minnimum
print(np.max(arr2d))#maximum

21
3.5
3.5
0.9574271077563381
2
5


In [82]:
#array comparision 
aa=np.array([1,2,3,4,5])
bb=np.array([6,7,3,9,5])
print(aa)
print(bb)


[1 2 3 4 5]
[6 7 3 9 5]


In [84]:
print(aa==bb) #compare each element of array 

[False False  True False  True]


In [85]:
print(np.array_equal(aa,bb)) #compare complete array

False


In [90]:
#11. broadcasting 
a=np.array([1,2,3,4,5])
b=np.array([3])
print(a)
print(b)
print(a+b)
arr2d =np.array([[2,3,4],[4,3,5]])
arr1d =np.array([2,3,4])
print(arr2d)
print(arr1d)
print("after adding a 1d and 2d array")
print(arr2d +arr1d)


[1 2 3 4 5]
[3]
[4 5 6 7 8]
[[2 3 4]
 [4 3 5]]
[2 3 4]
after adding a 1d and 2d array
[[4 6 8]
 [6 6 9]]


In [93]:
#handling nan and inf 
data = np.array([1,4,np.nan,6,np.inf])
print(data)
#for checking the nan and null value in data is present or not 
print(np.isnan(data))

#for replacing nan with number 
print(np.nan_to_num(data))

[ 1.  4. nan  6. inf]
[False False  True False False]
[1.00000000e+000 4.00000000e+000 0.00000000e+000 6.00000000e+000
 1.79769313e+308]


In [96]:
#save an array
arr = np.array([[2,3,4,5,6],[2,2,4,5,6]])
print(arr)
np.save('my_array.npy',arr)

[[2 3 4 5 6]
 [2 2 4 5 6]]


In [97]:
#load array
loadedarr = np.load('my_array.npy')
print(loadedarr)

[[2 3 4 5 6]
 [2 2 4 5 6]]
